import { NextFunction, Request, Response } from "express";
import bcrypt from "bcryptjs";
import pool from "../db/index.js";
import ApiError from "../utils/ApiError.js";
import ApiResponse from "../utils/ApiResponse.js";
import { DbErrorCodes, DatabaseError } from "../utils/DbError.js";

const SALT_ROUNDS = 12;

export async function createAdmin(req: Request, res: Response, next: NextFunction) {
  if (!req.body || Object.keys(req.body).length === 0) {
    return next(new ApiError(422, "Unprocessable Entity", "Body is missing"));
  }

  const { userName, userEmail, userContactNo, password, deptAbbreviation, adminLvl } = req.body;

  if ([userName, userEmail, password, deptAbbreviation, adminLvl].some((field) => !field)) {
    return next(new ApiError(422, "Unprocessable Entity", "All required fields must be provided"));
  }

  const hashedPassword = await bcrypt.hash(password, SALT_ROUNDS);
  const client = await pool.connect();
  ``;

  try {
    await client.query("BEGIN");

    const userQuery = `
      INSERT INTO users (user_name, user_email, user_contact_no, password, dept_abbreviation, role)
      VALUES ($1, $2, $3, $4, $5, $6) 
      RETURNING 
          user_id AS "userId", 
          user_name AS "userName", 
          user_email AS "userEmail", 
          user_contact_no AS "userContactNo",
          dept_abbreviation AS "deptAbbreviation",
          role,
          is_active AS "isActive";
    `;
    const userRes = await client.query(userQuery, [
      userName,
      userEmail,
      userContactNo,
      hashedPassword,
      deptAbbreviation,
      "admin"
    ]);

    const autoGeneratedId = userRes.rows[0].userId;

    const adminQuery = `
      INSERT INTO admin (user_id, admin_lvl) 
      VALUES ($1, $2) 
      RETURNING admin_lvl AS "adminLvl"
    `;
    const adminRes = await client.query(adminQuery, [autoGeneratedId, adminLvl]);

    const adminData = { ...userRes.rows[0], ...adminRes.rows[0] };
    await client.query("COMMIT");

    return res.status(201).json(new ApiResponse(201, adminData, "Admin created successfully"));
  } catch (err: unknown) {
    await client.query("ROLLBACK");

    const error = err as DatabaseError;

    if (error.code === DbErrorCodes.UNIQUE_VIOLATION) {
      return next(new ApiError(409, "Conflict", "User Email already exists"));
    }
    if (error.code === DbErrorCodes.FOREIGN_KEY_VIOLATION) {
      return next(
        new ApiError(409, "Conflict", "The specified department abbreviation does not exist")
      );
    }

    console.error("Transaction Error", error);
    return next(new ApiError(500, "Internal Server Error", "Failed to create Admin"));
  } finally {
    client.release();
  }
}

export async function addFaculty(req: Request, res: Response, next: NextFunction) {
  if (!req.body || Object.keys(req.body).length === 0) {
    return next(new ApiError(422, "Unprocessable Entity", "Body is missing"));
  }

  const {
    userName,
    userEmail,
    userContactNo,
    password,
    deptAbbreviation,
    designation,
    areaOfResearch
  } = req.body;

  if ([userName, userEmail, password, deptAbbreviation, designation].some((field) => !field)) {
    return next(new ApiError(422, "Unprocessable Entity", "All required fields must be provided"));
  }

  const hashedPassword = await bcrypt.hash(password, SALT_ROUNDS);
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    const userQuery = `
      INSERT INTO users (user_name, user_email, user_contact_no, password, dept_abbreviation, role)
      VALUES ($1, $2, $3, $4, $5, $6) 
      RETURNING 
          user_id AS "userId", 
          user_name AS "userName", 
          user_email AS "userEmail", 
          user_contact_no AS "userContactNo",
          dept_abbreviation AS "deptAbbreviation",
          role,
          is_active AS "isActive";
    `;
    const userRes = await client.query(userQuery, [
      userName,
      userEmail,
      userContactNo,
      hashedPassword,
      deptAbbreviation,
      "faculty"
    ]);

    const autoGeneratedId = userRes.rows[0].userId;

    const facultyQuery = `
      INSERT INTO faculty (user_id, designation, area_of_research) 
      VALUES ($1, $2, $3) 
      RETURNING designation, area_of_research AS "areaOfResearch"
    `;
    const facultyRes = await client.query(facultyQuery, [
      autoGeneratedId,
      designation,
      areaOfResearch
    ]);

    const facultyData = { ...userRes.rows[0], ...facultyRes.rows[0] };
    await client.query("COMMIT");

    return res.status(201).json(new ApiResponse(201, facultyData, "Faculty added successfully"));
  } catch (err: unknown) {
    await client.query("ROLLBACK");

    const error = err as DatabaseError;

    if (error.code === DbErrorCodes.UNIQUE_VIOLATION) {
      return next(new ApiError(409, "Conflict", "User Email already exists"));
    }
    if (error.code === DbErrorCodes.FOREIGN_KEY_VIOLATION) {
      return next(
        new ApiError(409, "Conflict", "The specified department abbreviation does not exist")
      );
    }

    console.error("Transaction Error:", error);
    return next(new ApiError(500, "Internal Server Error", "Database transaction failed"));
  } finally {
    client.release();
  }
}

export async function addStaff(req: Request, res: Response, next: NextFunction) {
  if (!req.body || Object.keys(req.body).length === 0) {
    return next(new ApiError(422, "Unprocessable Entity", "Body is missing"));
  }

  const { userName, userEmail, userContactNo, password, deptAbbreviation, jobTitle } = req.body;

  if ([userName, userEmail, password, deptAbbreviation, jobTitle].some((field) => !field)) {
    return next(new ApiError(422, "Unprocessable Entity", "All required fields must be provided"));
  }

  const hashedPassword = await bcrypt.hash(password, SALT_ROUNDS);
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    const userQuery = `
      INSERT INTO users (user_name, user_email, user_contact_no, password, dept_abbreviation, role)
      VALUES ($1, $2, $3, $4, $5, $6) 
      RETURNING 
          user_id AS "userId", 
          user_name AS "userName", 
          user_email AS "userEmail", 
          user_contact_no AS "userContactNo",
          dept_abbreviation AS "deptAbbreviation",
          role,
          is_active AS "isActive";
    `;
    const userRes = await client.query(userQuery, [
      userName,
      userEmail,
      userContactNo,
      hashedPassword,
      deptAbbreviation,
      "staff"
    ]);

    const autoGeneratedId = userRes.rows[0].userId;

    const staffQuery = `
      INSERT INTO staff (user_id, job_title) 
      VALUES ($1, $2) 
      RETURNING job_title AS "jobTitle"
    `;
    const staffRes = await client.query(staffQuery, [autoGeneratedId, jobTitle]);

    const staffData = { ...userRes.rows[0], ...staffRes.rows[0] };
    await client.query("COMMIT");

    return res.status(201).json(new ApiResponse(201, staffData, "Staff added successfully"));
  } catch (err: unknown) {
    await client.query("ROLLBACK");

    const error = err as DatabaseError;

    if (error.code === DbErrorCodes.UNIQUE_VIOLATION) {
      return next(new ApiError(409, "Conflict", "User Email already exists"));
    }
    if (error.code === DbErrorCodes.FOREIGN_KEY_VIOLATION) {
      return next(
        new ApiError(409, "Conflict", "The specified department abbreviation does not exist")
      );
    }

    console.error("Transaction Error:", error);
    return next(new ApiError(500, "Internal Server Error", "Database transaction failed"));
  } finally {
    client.release();
  }
}

// GET /api/v1/users
export async function getUsers(req: Request, res: Response, next: NextFunction) {
  // Default pagination values
  let limit = 20;
  let offset = 0;

  if (req.query.limit) {
    limit = parseInt(req.query.limit as string, 10);
    if (isNaN(limit)) limit = 20;
  }

  if (req.query.offset) {
    offset = parseInt(req.query.offset as string, 10);
    if (isNaN(offset)) offset = 0;
  }

  try {
    let conditionQuery = `WHERE 1=1`;
    const queryParams: any[] = [];
    let paramCounter = 1;

    // Search Parameter (case-insensitive partial match)
    if (req.query.search) {
      const searchTerm = `%${req.query.search}%`;
      conditionQuery += ` AND (user_name ILIKE $${paramCounter} OR user_email ILIKE $${paramCounter} OR user_contact_no ILIKE $${paramCounter})`;
      queryParams.push(searchTerm);
      paramCounter++;
    }

    // Filter = Department Abbreviation
    if (req.query.deptAbbreviation) {
      conditionQuery += ` AND dept_abbreviation = $${paramCounter}`;
      queryParams.push(req.query.deptAbbreviation);
      paramCounter++;
    }

    // Filter = Role
    if (req.query.role) {
      conditionQuery += ` AND role = $${paramCounter}`;
      queryParams.push(req.query.role);
      paramCounter++;
    }

    // Filter = Active Status
    if (req.query.isActive !== undefined) {
      conditionQuery += ` AND is_active = $${paramCounter}`;
      queryParams.push(req.query.isActive === "true");
      paramCounter++;
    }

    const dataQuery = `
      SELECT user_id, user_name, user_email, user_contact_no, dept_abbreviation, role, is_active
      FROM users
      ${conditionQuery}
      ORDER BY user_name ASC
      LIMIT $${paramCounter} OFFSET $${paramCounter + 1};
    `;

    const countQuery = `
      SELECT COUNT(*) 
      FROM users
      ${conditionQuery};
    `;

    const dataParams = [...queryParams, limit, offset];

    // Execute both queries concurrently
    const [dataResult, countResult] = await Promise.all([
      pool.query(dataQuery, dataParams),
      pool.query(countQuery, queryParams)
    ]);

    // Calculate pagination metadata
    const totalRecords = parseInt(countResult.rows[0].count, 10);
    const totalPages = Math.ceil(totalRecords / limit);
    const currentPage = Math.floor(offset / limit) + 1;

    const responsePayload = {
      data: dataResult.rows,
      meta: {
        currentPage,
        totalPages,
        totalRecords
      }
    };

    return res
      .status(200)
      .json(new ApiResponse(200, responsePayload, "Users fetched successfully"));
  } catch (error) {
    console.error("Error fetching users:", error);
    return next(new ApiError(500, "Internal Server Error", "Failed to fetch users"));
  }
}

export async function getSupervisingFaculty(req: Request, res: Response, next: NextFunction) {
  try {
    let queryText = `
        SELECT DISTINCT 
            u.user_id, 
            u.user_name, 
            u.user_email,
            u.dept_abbreviation 
        FROM users u
        JOIN project_faculty pf ON u.user_id = pf.faculty_id
        WHERE 1=1
    `;

    const queryParams: any[] = [];
    let paramCounter = 1;

    if (req.query.department) {
      queryText += ` AND u.dept_abbreviation = $${paramCounter}`;
      queryParams.push(req.query.department);
      paramCounter++;
    }

    queryText += ` ORDER BY u.user_name ASC;`;

    const result = await pool.query(queryText, queryParams);

    return res
      .status(200)
      .json(new ApiResponse(200, result.rows, "Supervising faculty fetched successfully"));
  } catch (error) {
    console.error("Error fetching supervising faculty:", error);
    return next(new ApiError(500, "Internal Server Error", "Failed to fetch faculty"));
  }
}

export async function getUserById(req: Request, res: Response, next: NextFunction) {
  const { id } = req.params;

  try {
    const query = `
      SELECT 
        u.user_id AS "userId", 
        u.user_name AS "userName", 
        u.user_email AS "userEmail", 
        u.user_contact_no AS "userContactNo", 
        u.dept_abbreviation AS "deptAbbreviation", 
        u.role, 
        u.is_active AS "isActive",
        a.admin_lvl AS "adminLvl",
        f.designation, 
        f.area_of_research AS "areaOfResearch",
        s.job_title AS "jobTitle"
      FROM users u
      LEFT JOIN admin a ON u.user_id = a.user_id
      LEFT JOIN faculty f ON u.user_id = f.user_id
      LEFT JOIN staff s ON u.user_id = s.user_id
      WHERE u.user_id = $1;
    `;

    const result = await pool.query(query, [id]);

    if (result.rowCount === 0) {
      return next(new ApiError(404, "Not Found", "User not found"));
    }

    const raw = result.rows[0];

    // here i am buildingg response object based on their actual role
    // NOTE: i know donot use any but donot have enogh time now
    const userData: any = {
      userId: raw.userId,
      userName: raw.userName,
      userEmail: raw.userEmail,
      userContactNo: raw.userContactNo,
      deptAbbreviation: raw.deptAbbreviation,
      role: raw.role,
      isActive: raw.isActive
    };

    if (raw.role === "admin") {
      userData.adminLvl = raw.adminLvl;
    } else if (raw.role === "faculty") {
      userData.designation = raw.designation;
      userData.areaOfResearch = raw.areaOfResearch;
    } else if (raw.role === "staff") {
      userData.jobTitle = raw.jobTitle;
    }

    return res.status(200).json(new ApiResponse(200, userData, "User fetched successfully"));
  } catch (error) {
    console.error("Error fetching user by ID:", error);
    return next(new ApiError(500, "Internal Server Error", "Failed to fetch user"));
  }
}

export async function updateUser(req: Request, res: Response, next: NextFunction) {
  const { id } = req.params;
  const updates = req.body;

  if (!updates || Object.keys(updates).length === 0) {
    return next(new ApiError(422, "Unprocessable Entity", "Body is missing or empty"));
  }

  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    const roleRes = await client.query(`SELECT role FROM users WHERE user_id = $1`, [id]);
    if (roleRes.rowCount === 0) {
      await client.query("ROLLBACK");
      return next(new ApiError(404, "Not Found", "User not found"));
    }
    const role = roleRes.rows[0].role;

    const baseFields = [
      "userName",
      "userEmail",
      "userContactNo",
      "deptAbbreviation",
      "isActive",
      "password"
    ];
    const baseUpdates: any = {};

    for (const key of baseFields) {
      if (updates[key] !== undefined) baseUpdates[key] = updates[key];
    }

    if (baseUpdates.password) {
      baseUpdates.password = await bcrypt.hash(baseUpdates.password, SALT_ROUNDS);
    }

    if (Object.keys(baseUpdates).length > 0) {
      const setCols = [];
      const values = [];
      let i = 1;

      for (const [k, v] of Object.entries(baseUpdates)) {
        // Convert camelCase keys to snake_case for the DB
        const colName = k.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
        setCols.push(`${colName} = $${i}`);
        values.push(v);
        i++;
      }
      values.push(id); // pushing id to used it in whre clause

      const updateUsersQuery = `UPDATE users SET ${setCols.join(", ")} WHERE user_id = $${i}`;
      await client.query(updateUsersQuery, values);
    }

    // now updating the specific role table
    if (role === "admin" && updates.adminLvl !== undefined) {
      await client.query(`UPDATE admin SET admin_lvl = $1 WHERE user_id = $2`, [
        updates.adminLvl,
        id
      ]);
    } else if (role === "faculty") {
      const facUpdates = [];
      const facVals = [];
      let i = 1;

      if (updates.designation !== undefined) {
        facUpdates.push(`designation = $${i++}`);
        facVals.push(updates.designation);
      }
      if (updates.areaOfResearch !== undefined) {
        facUpdates.push(`area_of_research = $${i++}`);
        facVals.push(updates.areaOfResearch);
      }

      if (facUpdates.length > 0) {
        facVals.push(id);
        await client.query(
          `UPDATE faculty SET ${facUpdates.join(", ")} WHERE user_id = $${i}`,
          facVals
        );
      }
    } else if (role === "staff" && updates.jobTitle !== undefined) {
      await client.query(`UPDATE staff SET job_title = $1 WHERE user_id = $2`, [
        updates.jobTitle,
        id
      ]);
    }

    await client.query("COMMIT");

    return res.status(200).json(new ApiResponse(200, null, "User updated successfully"));
  } catch (err: unknown) {
    await client.query("ROLLBACK");

    const error = err as DatabaseError;
    if (error.code === DbErrorCodes.UNIQUE_VIOLATION) {
      return next(new ApiError(409, "Conflict", "User Email already exists"));
    }
    if (error.code === DbErrorCodes.FOREIGN_KEY_VIOLATION) {
      return next(
        new ApiError(409, "Conflict", "The specified department abbreviation does not exist")
      );
    }

    console.error("Update Transaction Error:", error);
    return next(new ApiError(500, "Internal Server Error", "Failed to update user"));
  } finally {
    client.release();
  }
}

export async function deleteUser(req: Request, res: Response, next: NextFunction) {
  const { id } = req.params;
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    const roleRes = await client.query(`SELECT role FROM users WHERE user_id = $1`, [id]);
    if (roleRes.rowCount === 0) {
      await client.query("ROLLBACK");
      return next(new ApiError(404, "Not Found", "User not found"));
    }

    const role = roleRes.rows[0].role;

    if (role === "admin") {
      await client.query(`DELETE FROM admin WHERE user_id = $1`, [id]);
    } else if (role === "faculty") {
      await client.query(`DELETE FROM faculty WHERE user_id = $1`, [id]);
    } else if (role === "staff") {
      await client.query(`DELETE FROM staff WHERE user_id = $1`, [id]);
    }

    await client.query(`DELETE FROM users WHERE user_id = $1`, [id]);

    await client.query("COMMIT");

    return res.status(200).json(new ApiResponse(200, null, "User deleted successfully"));
  } catch (error) {
    await client.query("ROLLBACK");
    console.error("Delete Transaction Error:", error);
    return next(new ApiError(500, "Internal Server Error", "Failed to delete user"));
  } finally {
    client.release();
  }
}

export async function softDeleteUser(req: Request, res: Response, next: NextFunction) {
  const { id } = req.params;

  try {
    const query = `
      UPDATE users 
      SET is_active = false 
      WHERE user_id = $1 
      RETURNING user_id
    `;

    const result = await pool.query(query, [id]);

    if (result.rowCount === 0) {
      return next(new ApiError(404, "Not Found", "User not found"));
    }

    return res.status(200).json(new ApiResponse(200, null, "User successfully deactivated"));
  } catch (error) {
    console.error("Soft Delete Error:", error);
    return next(new ApiError(500, "Internal Server Error", "Failed to deactivate user"));
  }
}
