// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { usersUserId, type UsersUserId } from './Users.js';
import { z } from 'zod';

/** Represents the table public.admin */
export default interface Admin {
  user_id: UsersUserId;

  admin_lvl: number | null;
}

/** Represents the initializer for the table public.admin */
export interface AdminInitializer {
  user_id: UsersUserId;

  admin_lvl?: number | null;
}

/** Represents the mutator for the table public.admin */
export interface AdminMutator {
  user_id?: UsersUserId;

  admin_lvl?: number | null;
}

export const admin = z.object({
  user_id: usersUserId,
  admin_lvl: z.number().nullable(),
}) as unknown as z.Schema<Admin>;

export const adminInitializer = z.object({
  user_id: usersUserId,
  admin_lvl: z.number().optional().nullable(),
}) as unknown as z.Schema<AdminInitializer>;

export const adminMutator = z.object({
  user_id: usersUserId.optional(),
  admin_lvl: z.number().optional().nullable(),
}) as unknown as z.Schema<AdminMutator>;
