// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { usersId, type UsersId } from './Users.js';
import { departmentsId, type DepartmentsId } from './Departments.js';
import { z } from 'zod';

/** Represents the table public.admins */
export default interface Admins {
  id: UsersId;

  admin_level: number | null;

  department_id: DepartmentsId | null;
}

/** Represents the initializer for the table public.admins */
export interface AdminsInitializer {
  id: UsersId;

  /** Default value: 2 */
  admin_level?: number | null;

  department_id?: DepartmentsId | null;
}

/** Represents the mutator for the table public.admins */
export interface AdminsMutator {
  id?: UsersId;

  admin_level?: number | null;

  department_id?: DepartmentsId | null;
}

export const admins = z.object({
  id: usersId,
  admin_level: z.number().nullable(),
  department_id: departmentsId.nullable(),
}) as unknown as z.Schema<Admins>;

export const adminsInitializer = z.object({
  id: usersId,
  admin_level: z.number().optional().nullable(),
  department_id: departmentsId.optional().nullable(),
}) as unknown as z.Schema<AdminsInitializer>;

export const adminsMutator = z.object({
  id: usersId.optional(),
  admin_level: z.number().optional().nullable(),
  department_id: departmentsId.optional().nullable(),
}) as unknown as z.Schema<AdminsMutator>;
