// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.audit_logs */
export type AuditLogsLogId = number & { __brand: 'public.audit_logs' };

/** Represents the table public.audit_logs */
export default interface AuditLogs {
  log_id: AuditLogsLogId;

  table_name: string;

  action: string;

  old_data: unknown | null;

  new_data: unknown | null;

  changed_at: Date | null;
}

/** Represents the initializer for the table public.audit_logs */
export interface AuditLogsInitializer {
  /** Default value: nextval('audit_logs_log_id_seq'::regclass) */
  log_id?: AuditLogsLogId;

  table_name: string;

  action: string;

  old_data?: unknown | null;

  new_data?: unknown | null;

  /** Default value: CURRENT_TIMESTAMP */
  changed_at?: Date | null;
}

/** Represents the mutator for the table public.audit_logs */
export interface AuditLogsMutator {
  log_id?: AuditLogsLogId;

  table_name?: string;

  action?: string;

  old_data?: unknown | null;

  new_data?: unknown | null;

  changed_at?: Date | null;
}

export const auditLogsLogId = z.string() as unknown as z.Schema<AuditLogsLogId>;

export const auditLogs = z.object({
  log_id: auditLogsLogId,
  table_name: z.string(),
  action: z.string(),
  old_data: z.unknown().nullable(),
  new_data: z.unknown().nullable(),
  changed_at: z.date().nullable(),
}) as unknown as z.Schema<AuditLogs>;

export const auditLogsInitializer = z.object({
  log_id: auditLogsLogId.optional(),
  table_name: z.string(),
  action: z.string(),
  old_data: z.unknown().optional().nullable(),
  new_data: z.unknown().optional().nullable(),
  changed_at: z.date().optional().nullable(),
}) as unknown as z.Schema<AuditLogsInitializer>;

export const auditLogsMutator = z.object({
  log_id: auditLogsLogId.optional(),
  table_name: z.string().optional(),
  action: z.string().optional(),
  old_data: z.unknown().optional().nullable(),
  new_data: z.unknown().optional().nullable(),
  changed_at: z.date().optional().nullable(),
}) as unknown as z.Schema<AuditLogsMutator>;
