// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.department */
export type DepartmentDeptAbbreviation = string & { __brand: 'public.department' };

/** Represents the table public.department */
export default interface Department {
  dept_abbreviation: DepartmentDeptAbbreviation;

  dept_name: string;
}

/** Represents the initializer for the table public.department */
export interface DepartmentInitializer {
  dept_abbreviation: DepartmentDeptAbbreviation;

  dept_name: string;
}

/** Represents the mutator for the table public.department */
export interface DepartmentMutator {
  dept_abbreviation?: DepartmentDeptAbbreviation;

  dept_name?: string;
}

export const departmentDeptAbbreviation = z.string() as unknown as z.Schema<DepartmentDeptAbbreviation>;

export const department = z.object({
  dept_abbreviation: departmentDeptAbbreviation,
  dept_name: z.string(),
}) as unknown as z.Schema<Department>;

export const departmentInitializer = z.object({
  dept_abbreviation: departmentDeptAbbreviation,
  dept_name: z.string(),
}) as unknown as z.Schema<DepartmentInitializer>;

export const departmentMutator = z.object({
  dept_abbreviation: departmentDeptAbbreviation.optional(),
  dept_name: z.string().optional(),
}) as unknown as z.Schema<DepartmentMutator>;
