// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.departments */
export type DepartmentsId = string & { __brand: 'public.departments' };

/** Represents the table public.departments */
export default interface Departments {
  id: DepartmentsId;

  name: string;

  code: string;

  hod_id: string | null;

  description: string | null;

  created_at: Date;
}

/** Represents the initializer for the table public.departments */
export interface DepartmentsInitializer {
  /** Default value: gen_random_uuid() */
  id?: DepartmentsId;

  name: string;

  code: string;

  hod_id?: string | null;

  description?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date;
}

/** Represents the mutator for the table public.departments */
export interface DepartmentsMutator {
  id?: DepartmentsId;

  name?: string;

  code?: string;

  hod_id?: string | null;

  description?: string | null;

  created_at?: Date;
}

export const departmentsId = z.uuid() as unknown as z.Schema<DepartmentsId>;

export const departments = z.object({
  id: departmentsId,
  name: z.string(),
  code: z.string(),
  hod_id: z.uuid().nullable(),
  description: z.string().nullable(),
  created_at: z.date(),
}) as unknown as z.Schema<Departments>;

export const departmentsInitializer = z.object({
  id: departmentsId.optional(),
  name: z.string(),
  code: z.string(),
  hod_id: z.uuid().optional().nullable(),
  description: z.string().optional().nullable(),
  created_at: z.date().optional(),
}) as unknown as z.Schema<DepartmentsInitializer>;

export const departmentsMutator = z.object({
  id: departmentsId.optional(),
  name: z.string().optional(),
  code: z.string().optional(),
  hod_id: z.uuid().optional().nullable(),
  description: z.string().optional().nullable(),
  created_at: z.date().optional(),
}) as unknown as z.Schema<DepartmentsMutator>;
