// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { departmentDeptAbbreviation, type DepartmentDeptAbbreviation } from './Department.js';
import { z } from 'zod';

/** Identifier type for public.domains */
export type DomainsDomainId = string & { __brand: 'public.domains' };

/** Represents the table public.domains */
export default interface Domains {
  domain_id: DomainsDomainId;

  domain_name: string;

  domain_description: string | null;

  dept_abbreviation: DepartmentDeptAbbreviation;
}

/** Represents the initializer for the table public.domains */
export interface DomainsInitializer {
  domain_id: DomainsDomainId;

  domain_name: string;

  domain_description?: string | null;

  dept_abbreviation: DepartmentDeptAbbreviation;
}

/** Represents the mutator for the table public.domains */
export interface DomainsMutator {
  domain_id?: DomainsDomainId;

  domain_name?: string;

  domain_description?: string | null;

  dept_abbreviation?: DepartmentDeptAbbreviation;
}

export const domainsDomainId = z.string() as unknown as z.Schema<DomainsDomainId>;

export const domains = z.object({
  domain_id: domainsDomainId,
  domain_name: z.string(),
  domain_description: z.string().nullable(),
  dept_abbreviation: departmentDeptAbbreviation,
}) as unknown as z.Schema<Domains>;

export const domainsInitializer = z.object({
  domain_id: domainsDomainId,
  domain_name: z.string(),
  domain_description: z.string().optional().nullable(),
  dept_abbreviation: departmentDeptAbbreviation,
}) as unknown as z.Schema<DomainsInitializer>;

export const domainsMutator = z.object({
  domain_id: domainsDomainId.optional(),
  domain_name: z.string().optional(),
  domain_description: z.string().optional().nullable(),
  dept_abbreviation: departmentDeptAbbreviation.optional(),
}) as unknown as z.Schema<DomainsMutator>;
