// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { industryIndustryId, type IndustryIndustryId } from './Industry.js';
import { z } from 'zod';

/** Identifier type for public.external_superv */
export type ExternalSupervExtEmail = string & { __brand: 'public.external_superv' };

/** Represents the table public.external_superv */
export default interface ExternalSuperv {
  ext_email: ExternalSupervExtEmail;

  ext_name: string;

  ext_designation: string | null;

  industry_id: IndustryIndustryId;
}

/** Represents the initializer for the table public.external_superv */
export interface ExternalSupervInitializer {
  ext_email: ExternalSupervExtEmail;

  ext_name: string;

  ext_designation?: string | null;

  industry_id: IndustryIndustryId;
}

/** Represents the mutator for the table public.external_superv */
export interface ExternalSupervMutator {
  ext_email?: ExternalSupervExtEmail;

  ext_name?: string;

  ext_designation?: string | null;

  industry_id?: IndustryIndustryId;
}

export const externalSupervExtEmail = z.string() as unknown as z.Schema<ExternalSupervExtEmail>;

export const externalSuperv = z.object({
  ext_email: externalSupervExtEmail,
  ext_name: z.string(),
  ext_designation: z.string().nullable(),
  industry_id: industryIndustryId,
}) as unknown as z.Schema<ExternalSuperv>;

export const externalSupervInitializer = z.object({
  ext_email: externalSupervExtEmail,
  ext_name: z.string(),
  ext_designation: z.string().optional().nullable(),
  industry_id: industryIndustryId,
}) as unknown as z.Schema<ExternalSupervInitializer>;

export const externalSupervMutator = z.object({
  ext_email: externalSupervExtEmail.optional(),
  ext_name: z.string().optional(),
  ext_designation: z.string().optional().nullable(),
  industry_id: industryIndustryId.optional(),
}) as unknown as z.Schema<ExternalSupervMutator>;
