// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { usersId, type UsersId } from './Users.js';
import { departmentsId, type DepartmentsId } from './Departments.js';
import { z } from 'zod';

/** Represents the table public.faculty */
export default interface Faculty {
  id: UsersId;

  employee_id: string;

  designation: string | null;

  research_area: string | null;

  is_available: boolean | null;

  department_id: DepartmentsId | null;
}

/** Represents the initializer for the table public.faculty */
export interface FacultyInitializer {
  id: UsersId;

  employee_id: string;

  designation?: string | null;

  research_area?: string | null;

  /** Default value: true */
  is_available?: boolean | null;

  department_id?: DepartmentsId | null;
}

/** Represents the mutator for the table public.faculty */
export interface FacultyMutator {
  id?: UsersId;

  employee_id?: string;

  designation?: string | null;

  research_area?: string | null;

  is_available?: boolean | null;

  department_id?: DepartmentsId | null;
}

export const faculty = z.object({
  id: usersId,
  employee_id: z.string(),
  designation: z.string().nullable(),
  research_area: z.string().nullable(),
  is_available: z.boolean().nullable(),
  department_id: departmentsId.nullable(),
}) as unknown as z.Schema<Faculty>;

export const facultyInitializer = z.object({
  id: usersId,
  employee_id: z.string(),
  designation: z.string().optional().nullable(),
  research_area: z.string().optional().nullable(),
  is_available: z.boolean().optional().nullable(),
  department_id: departmentsId.optional().nullable(),
}) as unknown as z.Schema<FacultyInitializer>;

export const facultyMutator = z.object({
  id: usersId.optional(),
  employee_id: z.string().optional(),
  designation: z.string().optional().nullable(),
  research_area: z.string().optional().nullable(),
  is_available: z.boolean().optional().nullable(),
  department_id: departmentsId.optional().nullable(),
}) as unknown as z.Schema<FacultyMutator>;
