// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { usersUserId, type UsersUserId } from './Users.js';
import { z } from 'zod';

/** Represents the table public.faculty */
export default interface Faculty {
  user_id: UsersUserId;

  designation: string;

  area_of_research: string | null;
}

/** Represents the initializer for the table public.faculty */
export interface FacultyInitializer {
  user_id: UsersUserId;

  designation: string;

  area_of_research?: string | null;
}

/** Represents the mutator for the table public.faculty */
export interface FacultyMutator {
  user_id?: UsersUserId;

  designation?: string;

  area_of_research?: string | null;
}

export const faculty = z.object({
  user_id: usersUserId,
  designation: z.string(),
  area_of_research: z.string().nullable(),
}) as unknown as z.Schema<Faculty>;

export const facultyInitializer = z.object({
  user_id: usersUserId,
  designation: z.string(),
  area_of_research: z.string().optional().nullable(),
}) as unknown as z.Schema<FacultyInitializer>;

export const facultyMutator = z.object({
  user_id: usersUserId.optional(),
  designation: z.string().optional(),
  area_of_research: z.string().optional().nullable(),
}) as unknown as z.Schema<FacultyMutator>;
