// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { projectsProjectId, type ProjectsProjectId } from './Projects.js';
import { industryIndustryId, type IndustryIndustryId } from './Industry.js';
import { z } from 'zod';

/** Identifier type for public.grants */
export type GrantsGrantName = string & { __brand: 'public.grants' };

/** Represents the table public.grants */
export default interface Grants {
  project_id: ProjectsProjectId;

  grant_name: GrantsGrantName;

  recieved_date: Date;

  grant_amount: number | null;

  industry_id: IndustryIndustryId;
}

/** Represents the initializer for the table public.grants */
export interface GrantsInitializer {
  project_id: ProjectsProjectId;

  grant_name: GrantsGrantName;

  recieved_date: Date;

  grant_amount?: number | null;

  industry_id: IndustryIndustryId;
}

/** Represents the mutator for the table public.grants */
export interface GrantsMutator {
  project_id?: ProjectsProjectId;

  grant_name?: GrantsGrantName;

  recieved_date?: Date;

  grant_amount?: number | null;

  industry_id?: IndustryIndustryId;
}

export const grantsGrantName = z.string() as unknown as z.Schema<GrantsGrantName>;

export const grants = z.object({
  project_id: projectsProjectId,
  grant_name: grantsGrantName,
  recieved_date: z.date(),
  grant_amount: z.string().nullable(),
  industry_id: industryIndustryId,
}) as unknown as z.Schema<Grants>;

export const grantsInitializer = z.object({
  project_id: projectsProjectId,
  grant_name: grantsGrantName,
  recieved_date: z.date(),
  grant_amount: z.string().optional().nullable(),
  industry_id: industryIndustryId,
}) as unknown as z.Schema<GrantsInitializer>;

export const grantsMutator = z.object({
  project_id: projectsProjectId.optional(),
  grant_name: grantsGrantName.optional(),
  recieved_date: z.date().optional(),
  grant_amount: z.string().optional().nullable(),
  industry_id: industryIndustryId.optional(),
}) as unknown as z.Schema<GrantsMutator>;
