// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { studentsSeatNo, type StudentsSeatNo } from './Students.js';
import { projectsProjectId, type ProjectsProjectId } from './Projects.js';
import { z } from 'zod';

/** Identifier type for public.groups */
export type GroupsGroupId = string & { __brand: 'public.groups' };

/** Represents the table public.groups */
export default interface Groups {
  group_id: GroupsGroupId;

  group_leader: StudentsSeatNo;

  member_2: StudentsSeatNo | null;

  member_3: StudentsSeatNo | null;

  member_4: StudentsSeatNo | null;

  project_id: ProjectsProjectId | null;
}

/** Represents the initializer for the table public.groups */
export interface GroupsInitializer {
  group_id: GroupsGroupId;

  group_leader: StudentsSeatNo;

  member_2?: StudentsSeatNo | null;

  member_3?: StudentsSeatNo | null;

  member_4?: StudentsSeatNo | null;

  project_id?: ProjectsProjectId | null;
}

/** Represents the mutator for the table public.groups */
export interface GroupsMutator {
  group_id?: GroupsGroupId;

  group_leader?: StudentsSeatNo;

  member_2?: StudentsSeatNo | null;

  member_3?: StudentsSeatNo | null;

  member_4?: StudentsSeatNo | null;

  project_id?: ProjectsProjectId | null;
}

export const groupsGroupId = z.string() as unknown as z.Schema<GroupsGroupId>;

export const groups = z.object({
  group_id: groupsGroupId,
  group_leader: studentsSeatNo,
  member_2: studentsSeatNo.nullable(),
  member_3: studentsSeatNo.nullable(),
  member_4: studentsSeatNo.nullable(),
  project_id: projectsProjectId.nullable(),
}) as unknown as z.Schema<Groups>;

export const groupsInitializer = z.object({
  group_id: groupsGroupId,
  group_leader: studentsSeatNo,
  member_2: studentsSeatNo.optional().nullable(),
  member_3: studentsSeatNo.optional().nullable(),
  member_4: studentsSeatNo.optional().nullable(),
  project_id: projectsProjectId.optional().nullable(),
}) as unknown as z.Schema<GroupsInitializer>;

export const groupsMutator = z.object({
  group_id: groupsGroupId.optional(),
  group_leader: studentsSeatNo.optional(),
  member_2: studentsSeatNo.optional().nullable(),
  member_3: studentsSeatNo.optional().nullable(),
  member_4: studentsSeatNo.optional().nullable(),
  project_id: projectsProjectId.optional().nullable(),
}) as unknown as z.Schema<GroupsMutator>;
