// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { usersId, type UsersId } from './Users.js';
import { z } from 'zod';

/** Represents the table public.guests */
export default interface Guests {
  id: UsersId;

  organization_name: string | null;

  job_title: string | null;

  created_by: UsersId | null;

  expires_at: Date | null;
}

/** Represents the initializer for the table public.guests */
export interface GuestsInitializer {
  id: UsersId;

  organization_name?: string | null;

  job_title?: string | null;

  created_by?: UsersId | null;

  expires_at?: Date | null;
}

/** Represents the mutator for the table public.guests */
export interface GuestsMutator {
  id?: UsersId;

  organization_name?: string | null;

  job_title?: string | null;

  created_by?: UsersId | null;

  expires_at?: Date | null;
}

export const guests = z.object({
  id: usersId,
  organization_name: z.string().nullable(),
  job_title: z.string().nullable(),
  created_by: usersId.nullable(),
  expires_at: z.date().nullable(),
}) as unknown as z.Schema<Guests>;

export const guestsInitializer = z.object({
  id: usersId,
  organization_name: z.string().optional().nullable(),
  job_title: z.string().optional().nullable(),
  created_by: usersId.optional().nullable(),
  expires_at: z.date().optional().nullable(),
}) as unknown as z.Schema<GuestsInitializer>;

export const guestsMutator = z.object({
  id: usersId.optional(),
  organization_name: z.string().optional().nullable(),
  job_title: z.string().optional().nullable(),
  created_by: usersId.optional().nullable(),
  expires_at: z.date().optional().nullable(),
}) as unknown as z.Schema<GuestsMutator>;
