// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.industry */
export type IndustryIndustryId = string & { __brand: 'public.industry' };

/** Represents the table public.industry */
export default interface Industry {
  industry_id: IndustryIndustryId;

  industry_name: string;

  location: string | null;

  industry_type: string | null;

  industry_email: string | null;
}

/** Represents the initializer for the table public.industry */
export interface IndustryInitializer {
  industry_id: IndustryIndustryId;

  industry_name: string;

  location?: string | null;

  industry_type?: string | null;

  industry_email?: string | null;
}

/** Represents the mutator for the table public.industry */
export interface IndustryMutator {
  industry_id?: IndustryIndustryId;

  industry_name?: string;

  location?: string | null;

  industry_type?: string | null;

  industry_email?: string | null;
}

export const industryIndustryId = z.string() as unknown as z.Schema<IndustryIndustryId>;

export const industry = z.object({
  industry_id: industryIndustryId,
  industry_name: z.string(),
  location: z.string().nullable(),
  industry_type: z.string().nullable(),
  industry_email: z.string().nullable(),
}) as unknown as z.Schema<Industry>;

export const industryInitializer = z.object({
  industry_id: industryIndustryId,
  industry_name: z.string(),
  location: z.string().optional().nullable(),
  industry_type: z.string().optional().nullable(),
  industry_email: z.string().optional().nullable(),
}) as unknown as z.Schema<IndustryInitializer>;

export const industryMutator = z.object({
  industry_id: industryIndustryId.optional(),
  industry_name: z.string().optional(),
  location: z.string().optional().nullable(),
  industry_type: z.string().optional().nullable(),
  industry_email: z.string().optional().nullable(),
}) as unknown as z.Schema<IndustryMutator>;
