// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.pgmigrations */
export type PgmigrationsId = number & { __brand: 'public.pgmigrations' };

/** Represents the table public.pgmigrations */
export default interface Pgmigrations {
  id: PgmigrationsId;

  name: string;

  run_on: Date;
}

/** Represents the initializer for the table public.pgmigrations */
export interface PgmigrationsInitializer {
  /** Default value: nextval('pgmigrations_id_seq'::regclass) */
  id?: PgmigrationsId;

  name: string;

  run_on: Date;
}

/** Represents the mutator for the table public.pgmigrations */
export interface PgmigrationsMutator {
  id?: PgmigrationsId;

  name?: string;

  run_on?: Date;
}

export const pgmigrationsId = z.number() as unknown as z.Schema<PgmigrationsId>;

export const pgmigrations = z.object({
  id: pgmigrationsId,
  name: z.string(),
  run_on: z.date(),
}) as unknown as z.Schema<Pgmigrations>;

export const pgmigrationsInitializer = z.object({
  id: pgmigrationsId.optional(),
  name: z.string(),
  run_on: z.date(),
}) as unknown as z.Schema<PgmigrationsInitializer>;

export const pgmigrationsMutator = z.object({
  id: pgmigrationsId.optional(),
  name: z.string().optional(),
  run_on: z.date().optional(),
}) as unknown as z.Schema<PgmigrationsMutator>;
