// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.projects */
export type ProjectsProjectId = string & { __brand: 'public.projects' };

/** Represents the table public.projects */
export default interface Projects {
  project_id: ProjectsProjectId;

  project_title: string;

  academic_year: string;

  abstract: string;
}

/** Represents the initializer for the table public.projects */
export interface ProjectsInitializer {
  project_id: ProjectsProjectId;

  project_title: string;

  academic_year: string;

  /** Default value: 'Abstract pending submission...'::text */
  abstract?: string;
}

/** Represents the mutator for the table public.projects */
export interface ProjectsMutator {
  project_id?: ProjectsProjectId;

  project_title?: string;

  academic_year?: string;

  abstract?: string;
}

export const projectsProjectId = z.string() as unknown as z.Schema<ProjectsProjectId>;

export const projects = z.object({
  project_id: projectsProjectId,
  project_title: z.string(),
  academic_year: z.string(),
  abstract: z.string(),
}) as unknown as z.Schema<Projects>;

export const projectsInitializer = z.object({
  project_id: projectsProjectId,
  project_title: z.string(),
  academic_year: z.string(),
  abstract: z.string().optional(),
}) as unknown as z.Schema<ProjectsInitializer>;

export const projectsMutator = z.object({
  project_id: projectsProjectId.optional(),
  project_title: z.string().optional(),
  academic_year: z.string().optional(),
  abstract: z.string().optional(),
}) as unknown as z.Schema<ProjectsMutator>;
