// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { projectsProjectId, type ProjectsProjectId } from './Projects.js';
import { usersUserId, type UsersUserId } from './Users.js';
import { z } from 'zod';

/** Represents the table public.project_faculty */
export default interface ProjectFaculty {
  project_id: ProjectsProjectId;

  faculty_id: UsersUserId;

  supervisory_role: string;

  remark: string | null;
}

/** Represents the initializer for the table public.project_faculty */
export interface ProjectFacultyInitializer {
  project_id: ProjectsProjectId;

  faculty_id: UsersUserId;

  supervisory_role: string;

  remark?: string | null;
}

/** Represents the mutator for the table public.project_faculty */
export interface ProjectFacultyMutator {
  project_id?: ProjectsProjectId;

  faculty_id?: UsersUserId;

  supervisory_role?: string;

  remark?: string | null;
}

export const projectFaculty = z.object({
  project_id: projectsProjectId,
  faculty_id: usersUserId,
  supervisory_role: z.string(),
  remark: z.string().nullable(),
}) as unknown as z.Schema<ProjectFaculty>;

export const projectFacultyInitializer = z.object({
  project_id: projectsProjectId,
  faculty_id: usersUserId,
  supervisory_role: z.string(),
  remark: z.string().optional().nullable(),
}) as unknown as z.Schema<ProjectFacultyInitializer>;

export const projectFacultyMutator = z.object({
  project_id: projectsProjectId.optional(),
  faculty_id: usersUserId.optional(),
  supervisory_role: z.string().optional(),
  remark: z.string().optional().nullable(),
}) as unknown as z.Schema<ProjectFacultyMutator>;
