// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { projectsProjectId, type ProjectsProjectId } from './Projects.js';
import { domainsDomainId, type DomainsDomainId } from './Domains.js';
import { z } from 'zod';

/** Represents the table public.project_domain */
export default interface ProjectDomain {
  project_id: ProjectsProjectId;

  domain_id: DomainsDomainId;
}

/** Represents the initializer for the table public.project_domain */
export interface ProjectDomainInitializer {
  project_id: ProjectsProjectId;

  domain_id: DomainsDomainId;
}

/** Represents the mutator for the table public.project_domain */
export interface ProjectDomainMutator {
  project_id?: ProjectsProjectId;

  domain_id?: DomainsDomainId;
}

export const projectDomain = z.object({
  project_id: projectsProjectId,
  domain_id: domainsDomainId,
}) as unknown as z.Schema<ProjectDomain>;

export const projectDomainInitializer = z.object({
  project_id: projectsProjectId,
  domain_id: domainsDomainId,
}) as unknown as z.Schema<ProjectDomainInitializer>;

export const projectDomainMutator = z.object({
  project_id: projectsProjectId.optional(),
  domain_id: domainsDomainId.optional(),
}) as unknown as z.Schema<ProjectDomainMutator>;
