// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { projectsProjectId, type ProjectsProjectId } from './Projects.js';
import { industryIndustryId, type IndustryIndustryId } from './Industry.js';
import { z } from 'zod';

/** Represents the table public.project_industry */
export default interface ProjectIndustry {
  project_id: ProjectsProjectId;

  industry_id: IndustryIndustryId;

  association_type: string;
}

/** Represents the initializer for the table public.project_industry */
export interface ProjectIndustryInitializer {
  project_id: ProjectsProjectId;

  industry_id: IndustryIndustryId;

  association_type: string;
}

/** Represents the mutator for the table public.project_industry */
export interface ProjectIndustryMutator {
  project_id?: ProjectsProjectId;

  industry_id?: IndustryIndustryId;

  association_type?: string;
}

export const projectIndustry = z.object({
  project_id: projectsProjectId,
  industry_id: industryIndustryId,
  association_type: z.string(),
}) as unknown as z.Schema<ProjectIndustry>;

export const projectIndustryInitializer = z.object({
  project_id: projectsProjectId,
  industry_id: industryIndustryId,
  association_type: z.string(),
}) as unknown as z.Schema<ProjectIndustryInitializer>;

export const projectIndustryMutator = z.object({
  project_id: projectsProjectId.optional(),
  industry_id: industryIndustryId.optional(),
  association_type: z.string().optional(),
}) as unknown as z.Schema<ProjectIndustryMutator>;
