// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { projectsProjectId, type ProjectsProjectId } from './Projects.js';
import { externalSupervExtEmail, type ExternalSupervExtEmail } from './ExternalSuperv.js';
import { z } from 'zod';

/** Represents the table public.project_external */
export default interface ProjectExternal {
  project_id: ProjectsProjectId;

  ext_email: ExternalSupervExtEmail;

  industry_feedback: string | null;
}

/** Represents the initializer for the table public.project_external */
export interface ProjectExternalInitializer {
  project_id: ProjectsProjectId;

  ext_email: ExternalSupervExtEmail;

  industry_feedback?: string | null;
}

/** Represents the mutator for the table public.project_external */
export interface ProjectExternalMutator {
  project_id?: ProjectsProjectId;

  ext_email?: ExternalSupervExtEmail;

  industry_feedback?: string | null;
}

export const projectExternal = z.object({
  project_id: projectsProjectId,
  ext_email: externalSupervExtEmail,
  industry_feedback: z.string().nullable(),
}) as unknown as z.Schema<ProjectExternal>;

export const projectExternalInitializer = z.object({
  project_id: projectsProjectId,
  ext_email: externalSupervExtEmail,
  industry_feedback: z.string().optional().nullable(),
}) as unknown as z.Schema<ProjectExternalInitializer>;

export const projectExternalMutator = z.object({
  project_id: projectsProjectId.optional(),
  ext_email: externalSupervExtEmail.optional(),
  industry_feedback: z.string().optional().nullable(),
}) as unknown as z.Schema<ProjectExternalMutator>;
