// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { projectsProjectId, type ProjectsProjectId } from './Projects.js';
import { z } from 'zod';

/** Identifier type for public.resources */
export type ResourcesResourceName = string & { __brand: 'public.resources' };

/** Represents the table public.resources */
export default interface Resources {
  project_id: ProjectsProjectId;

  resource_name: ResourcesResourceName;

  resource_path: string;

  mime_type: string;
}

/** Represents the initializer for the table public.resources */
export interface ResourcesInitializer {
  project_id: ProjectsProjectId;

  resource_name: ResourcesResourceName;

  resource_path: string;

  mime_type: string;
}

/** Represents the mutator for the table public.resources */
export interface ResourcesMutator {
  project_id?: ProjectsProjectId;

  resource_name?: ResourcesResourceName;

  resource_path?: string;

  mime_type?: string;
}

export const resourcesResourceName = z.string() as unknown as z.Schema<ResourcesResourceName>;

export const resources = z.object({
  project_id: projectsProjectId,
  resource_name: resourcesResourceName,
  resource_path: z.string(),
  mime_type: z.string(),
}) as unknown as z.Schema<Resources>;

export const resourcesInitializer = z.object({
  project_id: projectsProjectId,
  resource_name: resourcesResourceName,
  resource_path: z.string(),
  mime_type: z.string(),
}) as unknown as z.Schema<ResourcesInitializer>;

export const resourcesMutator = z.object({
  project_id: projectsProjectId.optional(),
  resource_name: resourcesResourceName.optional(),
  resource_path: z.string().optional(),
  mime_type: z.string().optional(),
}) as unknown as z.Schema<ResourcesMutator>;
