// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { usersUserId, type UsersUserId } from './Users.js';
import { z } from 'zod';

/** Represents the table public.staff */
export default interface Staff {
  user_id: UsersUserId;

  job_title: string;
}

/** Represents the initializer for the table public.staff */
export interface StaffInitializer {
  user_id: UsersUserId;

  job_title: string;
}

/** Represents the mutator for the table public.staff */
export interface StaffMutator {
  user_id?: UsersUserId;

  job_title?: string;
}

export const staff = z.object({
  user_id: usersUserId,
  job_title: z.string(),
}) as unknown as z.Schema<Staff>;

export const staffInitializer = z.object({
  user_id: usersUserId,
  job_title: z.string(),
}) as unknown as z.Schema<StaffInitializer>;

export const staffMutator = z.object({
  user_id: usersUserId.optional(),
  job_title: z.string().optional(),
}) as unknown as z.Schema<StaffMutator>;
