// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { usersId, type UsersId } from './Users.js';
import { departmentsId, type DepartmentsId } from './Departments.js';
import { z } from 'zod';

/** Represents the table public.staff */
export default interface Staff {
  id: UsersId;

  staff_id: string;

  desk_location: string | null;

  office_extension: string | null;

  department_id: DepartmentsId | null;
}

/** Represents the initializer for the table public.staff */
export interface StaffInitializer {
  id: UsersId;

  staff_id: string;

  desk_location?: string | null;

  office_extension?: string | null;

  department_id?: DepartmentsId | null;
}

/** Represents the mutator for the table public.staff */
export interface StaffMutator {
  id?: UsersId;

  staff_id?: string;

  desk_location?: string | null;

  office_extension?: string | null;

  department_id?: DepartmentsId | null;
}

export const staff = z.object({
  id: usersId,
  staff_id: z.string(),
  desk_location: z.string().nullable(),
  office_extension: z.string().nullable(),
  department_id: departmentsId.nullable(),
}) as unknown as z.Schema<Staff>;

export const staffInitializer = z.object({
  id: usersId,
  staff_id: z.string(),
  desk_location: z.string().optional().nullable(),
  office_extension: z.string().optional().nullable(),
  department_id: departmentsId.optional().nullable(),
}) as unknown as z.Schema<StaffInitializer>;

export const staffMutator = z.object({
  id: usersId.optional(),
  staff_id: z.string().optional(),
  desk_location: z.string().optional().nullable(),
  office_extension: z.string().optional().nullable(),
  department_id: departmentsId.optional().nullable(),
}) as unknown as z.Schema<StaffMutator>;
