// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { departmentDeptAbbreviation, type DepartmentDeptAbbreviation } from './Department.js';
import { z } from 'zod';

/** Identifier type for public.students */
export type StudentsSeatNo = string & { __brand: 'public.students' };

/** Represents the table public.students */
export default interface Students {
  seat_no: StudentsSeatNo;

  std_name: string;

  std_email: string;

  batch: string;

  dept_abbreviation: DepartmentDeptAbbreviation | null;
}

/** Represents the initializer for the table public.students */
export interface StudentsInitializer {
  seat_no: StudentsSeatNo;

  std_name: string;

  std_email: string;

  batch: string;

  dept_abbreviation?: DepartmentDeptAbbreviation | null;
}

/** Represents the mutator for the table public.students */
export interface StudentsMutator {
  seat_no?: StudentsSeatNo;

  std_name?: string;

  std_email?: string;

  batch?: string;

  dept_abbreviation?: DepartmentDeptAbbreviation | null;
}

export const studentsSeatNo = z.string() as unknown as z.Schema<StudentsSeatNo>;

export const students = z.object({
  seat_no: studentsSeatNo,
  std_name: z.string(),
  std_email: z.string(),
  batch: z.string(),
  dept_abbreviation: departmentDeptAbbreviation.nullable(),
}) as unknown as z.Schema<Students>;

export const studentsInitializer = z.object({
  seat_no: studentsSeatNo,
  std_name: z.string(),
  std_email: z.string(),
  batch: z.string(),
  dept_abbreviation: departmentDeptAbbreviation.optional().nullable(),
}) as unknown as z.Schema<StudentsInitializer>;

export const studentsMutator = z.object({
  seat_no: studentsSeatNo.optional(),
  std_name: z.string().optional(),
  std_email: z.string().optional(),
  batch: z.string().optional(),
  dept_abbreviation: departmentDeptAbbreviation.optional().nullable(),
}) as unknown as z.Schema<StudentsMutator>;
