// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.test */
export type TestId = number & { __brand: 'public.test' };

/** Represents the table public.test */
export default interface Test {
  id: TestId;

  name: string;

  created_at: Date | null;
}

/** Represents the initializer for the table public.test */
export interface TestInitializer {
  /** Default value: nextval('test_id_seq'::regclass) */
  id?: TestId;

  name: string;

  /** Default value: now() */
  created_at?: Date | null;
}

/** Represents the mutator for the table public.test */
export interface TestMutator {
  id?: TestId;

  name?: string;

  created_at?: Date | null;
}

export const testId = z.number() as unknown as z.Schema<TestId>;

export const test = z.object({
  id: testId,
  name: z.string(),
  created_at: z.date().nullable(),
}) as unknown as z.Schema<Test>;

export const testInitializer = z.object({
  id: testId.optional(),
  name: z.string(),
  created_at: z.date().optional().nullable(),
}) as unknown as z.Schema<TestInitializer>;

export const testMutator = z.object({
  id: testId.optional(),
  name: z.string().optional(),
  created_at: z.date().optional().nullable(),
}) as unknown as z.Schema<TestMutator>;
