// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { departmentDeptAbbreviation, type DepartmentDeptAbbreviation } from './Department.js';
import { z } from 'zod';

/** Identifier type for public.users */
export type UsersUserId = string & { __brand: 'public.users' };

/** Represents the table public.users */
export default interface Users {
  user_id: UsersUserId;

  user_name: string;

  user_email: string;

  user_contact_no: string | null;

  password: string;

  dept_abbreviation: DepartmentDeptAbbreviation;

  is_active: boolean | null;

  role: string;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  user_id: UsersUserId;

  user_name: string;

  user_email: string;

  user_contact_no?: string | null;

  password: string;

  dept_abbreviation: DepartmentDeptAbbreviation;

  /** Default value: true */
  is_active?: boolean | null;

  role: string;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  user_id?: UsersUserId;

  user_name?: string;

  user_email?: string;

  user_contact_no?: string | null;

  password?: string;

  dept_abbreviation?: DepartmentDeptAbbreviation;

  is_active?: boolean | null;

  role?: string;
}

export const usersUserId = z.string() as unknown as z.Schema<UsersUserId>;

export const users = z.object({
  user_id: usersUserId,
  user_name: z.string(),
  user_email: z.string(),
  user_contact_no: z.string().nullable(),
  password: z.string(),
  dept_abbreviation: departmentDeptAbbreviation,
  is_active: z.boolean().nullable(),
  role: z.string(),
}) as unknown as z.Schema<Users>;

export const usersInitializer = z.object({
  user_id: usersUserId,
  user_name: z.string(),
  user_email: z.string(),
  user_contact_no: z.string().optional().nullable(),
  password: z.string(),
  dept_abbreviation: departmentDeptAbbreviation,
  is_active: z.boolean().optional().nullable(),
  role: z.string(),
}) as unknown as z.Schema<UsersInitializer>;

export const usersMutator = z.object({
  user_id: usersUserId.optional(),
  user_name: z.string().optional(),
  user_email: z.string().optional(),
  user_contact_no: z.string().optional().nullable(),
  password: z.string().optional(),
  dept_abbreviation: departmentDeptAbbreviation.optional(),
  is_active: z.boolean().optional().nullable(),
  role: z.string().optional(),
}) as unknown as z.Schema<UsersMutator>;
