// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'public.users' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  user_name: string;

  email: string;

  password: string;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: gen_random_uuid() */
  id?: UsersId;

  user_name: string;

  email: string;

  password: string;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  user_name?: string;

  email?: string;

  password?: string;
}

export const usersId = z.uuid() as unknown as z.Schema<UsersId>;

export const users = z.object({
  id: usersId,
  user_name: z.string(),
  email: z.string(),
  password: z.string(),
}) as unknown as z.Schema<Users>;

export const usersInitializer = z.object({
  id: usersId.optional(),
  user_name: z.string(),
  email: z.string(),
  password: z.string(),
}) as unknown as z.Schema<UsersInitializer>;

export const usersMutator = z.object({
  id: usersId.optional(),
  user_name: z.string().optional(),
  email: z.string().optional(),
  password: z.string().optional(),
}) as unknown as z.Schema<UsersMutator>;
